<?php

/**
 * KFZ-Kennzeichen für deutsche Städte und Landkreise.
 *
 * Schlüssel: Stadtname (exakt wie in regional_partner.name oder als häufiger Schreibweise).
 * Wert: KFZ-Kennzeichen (Großbuchstaben).
 *
 * Wenn ein Regionalpartner nicht hier aufgeführt ist oder ein mehrteiliger Name hat
 * (z.B. "Leipzig/Halle"), sollte slug_short manuell in regional_partner gepflegt werden.
 */

return [

    // Stadtkreise / Kreisfreie Städte
    'Aachen'              => 'AC',
    'Augsburg'            => 'A',
    'Berlin'              => 'B',
    'Bielefeld'           => 'BI',
    'Bochum'              => 'BO',
    'Bonn'                => 'BN',
    'Brandenburg'         => 'BRB',
    'Braunschweig'        => 'BS',
    'Bremen'              => 'HB',
    'Bremerhaven'         => 'HBR',
    'Chemnitz'            => 'C',
    'Cottbus'             => 'CB',
    'Darmstadt'           => 'DA',
    'Dessau-Roßlau'       => 'DE',
    'Dortmund'            => 'DO',
    'Dresden'             => 'DD',
    'Duisburg'            => 'DU',
    'Düsseldorf'          => 'D',
    'Erfurt'              => 'EF',
    'Erlangen'            => 'ER',
    'Essen'               => 'E',
    'Frankfurt am Main'   => 'F',
    'Frankfurt'           => 'F',
    'Freiburg'            => 'FR',
    'Freiburg im Breisgau' => 'FR',
    'Fürth'               => 'FÜ',
    'Gelsenkirchen'       => 'GE',
    'Göttingen'           => 'GÖ',
    'Hagen'               => 'HA',
    'Halle'               => 'HAL',
    'Hamburg'             => 'HH',
    'Hamm'                => 'HAM',
    'Hannover'            => 'H',
    'Heidelberg'          => 'HD',
    'Heilbronn'           => 'HN',
    'Herne'               => 'HER',
    'Ingolstadt'          => 'IN',
    'Jena'                => 'J',
    'Karlsruhe'           => 'KA',
    'Kassel'              => 'KS',
    'Kiel'                => 'KI',
    'Koblenz'             => 'KO',
    'Köln'                => 'K',
    'Krefeld'             => 'KR',
    'Leipzig'             => 'L',
    'Leverkusen'          => 'LEV',
    'Lübeck'              => 'HL',
    'Ludwigshafen'        => 'LU',
    'Magdeburg'           => 'MD',
    'Mainz'               => 'MZ',
    'Mannheim'            => 'MA',
    'Mönchengladbach'     => 'MG',
    'Mülheim'             => 'MH',
    'München'             => 'M',
    'Münster'             => 'MS',
    'Neuss'               => 'NE',
    'Nürnberg'            => 'N',
    'Oberhausen'          => 'OB',
    'Offenbach'           => 'OF',
    'Oldenburg'           => 'OL',
    'Osnabrück'           => 'OS',
    'Pforzheim'           => 'PF',
    'Potsdam'             => 'P',
    'Regensburg'          => 'R',
    'Remscheid'           => 'RS',
    'Rostock'             => 'HRO',
    'Saarbrücken'         => 'SB',
    'Salzgitter'          => 'SZ',
    'Siegen'              => 'SI',
    'Solingen'            => 'SG',
    'Stuttgart'           => 'S',
    'Trier'               => 'TR',
    'Ulm'                 => 'UL',
    'Wiesbaden'           => 'WI',
    'Wolfsburg'           => 'WOB',
    'Wuppertal'           => 'W',
    'Würzburg'            => 'WÜ',

    // Häufige Landkreise / Regionen mit FLL-Relevanz
    'Aschaffenburg'       => 'AB',
    'Ansbach'             => 'AN',
    'Bamberg'             => 'BA',
    'Bayreuth'            => 'BT',
    'Berchtesgadener Land' => 'BGL',
    'Böblingen'           => 'BB',
    'Cloppenburg'         => 'CLP',
    'Coburg'              => 'CO',
    'Delmenhorst'         => 'DEL',
    'Emden'               => 'EMD',
    'Esslingen'           => 'ES',
    'Gießen'              => 'GI',
    'Göppingen'           => 'GP',
    'Gütersloh'           => 'GT',
    'Herford'             => 'HF',
    'Kaiserslautern'      => 'KL',
    'Konstanz'            => 'KN',
    'Landshut'            => 'LA',
    'Lörrach'             => 'LÖ',
    'Ludwigsburg'         => 'LB',
    'Lüneburg'            => 'LG',
    'Marburg'             => 'MR',
    'Minden'              => 'MI',
    'Neu-Ulm'             => 'NU',
    'Ortenau'             => 'OG',
    'Paderborn'           => 'PB',
    'Recklinghausen'      => 'RE',
    'Reutlingen'          => 'RT',
    'Rhein-Neckar'        => 'HD',
    'Rosenheim'           => 'RO',
    'Rottweil'            => 'RW',
    'Schwäbisch Gmünd'    => 'AA',
    'Schweinfurt'         => 'SW',
    'Schwerin'            => 'SN',
    'Straubing'           => 'SR',
    'Tübingen'            => 'TÜ',
    'Tuttlingen'          => 'TUT',
    'Unna'                => 'UN',
    'Villingen-Schwenningen' => 'VS',
    'Waiblingen'          => 'WN',
    'Weimar'              => 'WE',
    'Wesel'               => 'WES',
    'Worms'               => 'WO',
    'Zwickau'             => 'Z',
];
